### ISSUE TITLE
Getting error when i want to save page.

### ISSUE THREAD

**Issue by trk** [adrianbj/CustomUploadNames#3] opened 2017-09-22 12:10 UTC
Getting error when i want to save page (not trying to upload file only saving page). I am using new Fieldtype on this page ``FieldtypeFieldsetPage`` maybe problem cause from this.

![ekran resmi 2017-09-22 15 06 16](https://user-images.githubusercontent.com/455983/30743739-a2474e10-9fa7-11e7-8cb2-5def679d901d.png)

ProcessWire 3.0.75
PHP 7.1
Macos Sierra

**Comment by adrianbj** [comment] 2017-09-22 12:57
Hi @trk - thanks for the report. I think your hunch is correct. That line checks for the id of a repeater item. The problem is that FieldtypeFieldsetPage extends FieldtypeRepeater, so my code incorrectly identifies this as a repeater field. 

I will try to get a fix for this shortly (I haven't yet experimented with FieldtypeFieldsetPage fields), but in the meantime, could you please confirm that this is just a notice and doesn't actually break anything?

**Comment by trk** [comment] 2017-09-22 13:09
Its look like not breaking anything but there are lots of error.
![ekran resmi 2017-09-22 16 08 29](https://user-images.githubusercontent.com/455983/30745862-63035f9c-9fb0-11e7-8554-62c26ff66882.png)

**Comment by adrianbj** [comment] 2017-09-27 16:24
Hi @trk - this be fixed in the latest version. Please reopen if you have any further problems with it.

**Comment by adrianbj** [comment] 2017-09-28 02:34
Actually, I need to revisit this - the errors are gone, but it's not actually dealing with the new FieldtypeFieldsetPage fields - I will try again tomorrow.

**Comment by adrianbj** [comment] 2017-09-28 17:23
Ok, the latest version adds proper support for FieldtypeFieldsetPage fields.

Could you please test and close if everything is OK, or let me know if you still find any problems.

Thanks!

**Comment by adrianbj** [comment] 2017-10-19 17:09
@trk - I haven't heard back from you for a while, so I am going to assume everything is now working ok, but please reopen if you do find outstanding issues.

**Closed by adrianbj** 2017-10-19 17:10 UTC

**Comment by trk** [comment] 2017-10-20 14:42
Sorry @adrianbj, busy with a module. It seems there is no error. I will reopen if i see same error.
